services:
  - type: web
    name: contrax_backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker contrax_novo.main:app --bind 0.0.0.0:$PORT"
